import { useCallback, useEffect, useState } from "react";
import { desktopApi } from "../../lib/desktop-api";
import { useI18n } from "../../i18n";
import { emptyWorkspaceTopology, replaceWorkspacePage, selectWorkspace, type WorkspaceRecord } from "../../models/workspace";

interface Props { profileId: string; selectedId?: string; onSelect(id: string): void; }
export function WorkspaceTopologyPanel({ profileId, selectedId, onSelect }: Props) {
 const { t } = useI18n();
 const [topology,setTopology]=useState(()=>emptyWorkspaceTopology(profileId)); const [path,setPath]=useState(""); const [deviceId,setDeviceId]=useState(""); const [connectionId,setConnectionId]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState<string>();
 const refresh=useCallback(async()=>{ setBusy(true);setError(undefined); try { const [local,authorized] = await Promise.all([desktopApi.gatewayControl<unknown>("workspace.list"), desktopApi.callGateway<unknown>(profileId,"workspace",{version:"fabric.control.v1",action:"list"})]); const records:WorkspaceRecord[]=[]; if(Array.isArray(local)){for(const item of local){const value=item as Record<string,unknown>;if(typeof value.id==="string"&&typeof value.path==="string")records.push({layer:"registry",id:value.id,path:value.path,mode:value.mode==="permanent"?"permanent":"lease",generation:typeof value.generation==="number"?value.generation:1,expiresAt:typeof value.expiresAt==="number"?value.expiresAt:undefined,status:"active"});}} const data=authorized as {data?:{workspaces?:unknown[]}}; for(const item of data?.data?.workspaces??[]){const value=item as Record<string,unknown>;if(typeof value.workspaceId==="string"&&typeof value.deviceId==="string")records.push({layer:"authorized",id:value.workspaceId,path:typeof value.path==="string"?value.path:value.workspaceId,authorized:true,status:"authorized"});} setTopology(replaceWorkspacePage(emptyWorkspaceTopology(profileId),{records,nextCursor:records.length,hasMore:false})); } catch(value){setError(value instanceof Error?value.message:String(value));} finally{setBusy(false);} },[profileId]);
 useEffect(()=>{void refresh();},[refresh]);
 async function mutate(action:string){setBusy(true);setError(undefined);try{const item=topology.records.find((record)=>record.id===selectedId);if(action==="register")await desktopApi.gatewayControl("workspace.register",{target:path,ttlSeconds:300});else if(action==="renew") {if(item?.layer!=="registry")throw new Error(t("selectLocalWorkspace"));await desktopApi.gatewayControl("workspace.renew",{target:item.path,ttlSeconds:300,expectedGeneration:item.generation});}else if(action==="remove"){if(item?.layer!=="registry")throw new Error(t("selectLocalWorkspace"));if(!window.confirm("Remove this local workspace lease?"))return;await desktopApi.gatewayControl("workspace.remove",{target:item.path,expectedGeneration:item.generation});}else if(action==="bind"){if(item?.layer!=="authorized")throw new Error(t("selectAuthorizedWorkspace"));if(!deviceId||!connectionId)throw new Error(t("deviceConnectionRequired"));const response=await desktopApi.callGateway<{data?:{binding?:Record<string,unknown>}}>(profileId,"workspace",{version:"fabric.control.v1",action:"bind",workspaceId:item.id,deviceId,connectionId,expectedConnectionGeneration:1,expectedWorkspaceGeneration:1,requestedTtlMs:60000});const binding=response.data?.binding;if(binding&&typeof binding.bindingId==="string"){setTopology(value=>({...value,records:[...value.records,{layer:"binding",id:binding.bindingId as string,workspaceId:item.id,deviceId,connectionId,revision:typeof binding.revision==="number"?binding.revision:0,generation:1,expiresAt:typeof binding.expiresAt==="number"?binding.expiresAt:undefined,status:"active"}]}));}}else if(action==="unbind"){if(item?.layer!=="binding")throw new Error(t("selectBinding"));if(!window.confirm("Unbind this Fabric workspace?"))return;await desktopApi.callGateway(profileId,"workspace",{version:"fabric.control.v1",action:"unbind",workspaceBindingId:item.id,expectedRevision:item.revision});}await refresh();}catch(value){setError(/generation|revision|conflict/i.test(String(value))?t("workspaceChanged"):value instanceof Error?value.message:String(value));}finally{setBusy(false);}}
 const selected=topology.records.find((record)=>record.id===selectedId); const label=(record: WorkspaceRecord)=>record.layer==="binding"?record.workspaceId:record.path; const layerLabel=(record: WorkspaceRecord)=>record.layer==="registry"?t("registered"):record.layer==="authorized"?t("authorized"):t("binding"); return <section className="panel"><div className="panel-heading"><div><h2>{t("workspaces")}</h2><p>{t("registeredWorkspaceHint")}</p></div><button disabled={busy} onClick={()=>void refresh()}>{t("refreshList")}</button></div><div className="form-row"><label>{t("workspacePath")}<input value={path} onChange={event=>setPath(event.target.value)} placeholder={t("workspacePathPlaceholder")}/></label><label>{t("deviceId")}<input value={deviceId} onChange={event=>setDeviceId(event.target.value)}/></label><label>{t("connectionId")}<input value={connectionId} onChange={event=>setConnectionId(event.target.value)}/></label><button className="primary-action" disabled={!path||busy} onClick={()=>void mutate("register")}>{t("registerLease")}</button><button disabled={!selected||busy} onClick={()=>void mutate("renew")}>{t("renew")}</button><button disabled={!selected||busy} onClick={()=>void mutate("remove")}>{t("remove")}</button><button disabled={!selected||busy} onClick={()=>void mutate("bind")}>{t("bind")}</button><button disabled={!selected||busy} onClick={()=>void mutate("unbind")}>{t("unbind")}</button></div>{error&&<div className="error-box" role="alert">{error}</div>}<div className="workspace-list">{topology.records.length===0?<div className="compact-empty">{t("noWorkspaces")}</div>:topology.records.map(record=><button key={`${record.layer}:${record.id}`} className={selectedId===record.id?"workspace-row selected":"workspace-row"} onClick={()=>{const next=selectWorkspace(topology,record.id);setTopology(next);onSelect(record.id);}}><strong>{label(record)}</strong><span>{layerLabel(record)} · {record.status}{record.layer!=="authorized"?` · ${t("generation")} ${record.generation}`:""}</span></button>)}</div></section>;
}
